### PR TITLE
Updated a gif to be smaller with no noticeable jump.

### PR DESCRIPTION
**Pull request by syntholly**
There was a small jump in the gif and just wanted to clean it up a bit. It's only minor, but hopefully it helps.

### CODE REVIEW

**Comment by syntholly** [comment]
I noticed a few ideas on HackerNews that could be incorporated. It's all personal thoughts, I'm happy to play around with it a bit more.

**Comment by noximo** [comment]
Thanks! I merged your changes.

**Comment by syntholly** [comment]
Sorry @trosh, I have to correct your slightly rude comment here. 

`It's`, in this context, is correct, not `its`. 

`It's` expands to `it is`, which would make it `it is all personal thoughts` - my intention.

**Comment by trosh** [comment]
Sorry, I'm talking about the “it's own color” bit, which should be “its”. Thought the comment placement was enough and didn't want to burden the message.

**Comment by trosh** [comment]
OK I thought I'd placed the comment in the diff; apparently not, sorry. I meant README.md line 7.

**Comment by syntholly** [comment]
Apologies, I was a bit brash too. It's such a small thing I won't bother with it, maybe next time I contribute though! Thanks for your input.

**Pull request merged**
